site_name: Teodor Nikolov
site_url: https://www.teonikolov.com/

# Repository
repo_name: teonikolov/website
repo_url: https://github.com/teonikolov/website
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.footer
    - navigation.tabs
    - content.action.edit
    - content.action.view
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - awesome-pages
  - mkdocs-video
  - social
  - macros
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
        permalink: "🔗&#xFE0E;"
        toc_depth: 3
