site_name: Teodor Nikolov
theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.footer
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - awesome-pages
  - mkdocs-video
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
        permalink: "🔗&#xFE0E;"
        toc_depth: 3
